### ISSUE TITLE
Missing part from address

### ISSUE THREAD

**Issue by woywie87** [ahmedsaleh210/geocoding_resolver#2]
When I want to display address in my custom format, from AddressDetails object, there is no one part of address which is visible in "displayName" property. In this case is street name.
![Zrzut ekranu 2023-10-31 123807](https://github.com/ahmedsaleh210/geocoding_resolver/assets/9823834/b891119d-fb7b-42c2-8b73-437a23a5552e)

**Comment by ahmedsaleh210** [comment]
It's Not available in OSM API, but you can achieve what you want using (split) function
