### ISSUE TITLE
Package Required Updates

### ISSUE THREAD

**Issue by moha-b** [ahmedsaleh210/geocoding_resolver#3]
Please ensure to update the package to the latest version for all necessary improvements and bug fixes.

```shall
Because every version of geocoding_resolver depends on http ^0.13.5 and lottie 3.1.2 depends on http ^1.0.0, geocoding_resolver is incompatible with lottie 3.1.2.
And because no versions of lottie match >3.1.2 <4.0.0, geocoding_resolver is incompatible with lottie ^3.1.2.
So, because alquranalkareem depends on both lottie ^3.1.2 and geocoding_resolver ^0.0.3+2, version solving failed.
```

**Comment by moha-b** [comment]
I am closing this cause the package is out of maintenance

**Comment by pratikpwr** [comment]
> I am closing this cause the package is out of maintenance

did you find any alternative package to this

**Comment by moha-b** [comment]
> > I am closing this cause the package is out of maintenance
> 
> did you find any alternative package to this

I use this [geocoding](https://pub.dev/packages/geocoding) in most of my project but the replacement was this [nominatim_geocoding](https://pub.dev/packages/nominatim_geocoding)
